[package]
name = "pratt-parser"
version = "0.1.0"
authors = ["= <andyyu2004@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "5.0.4"
lexer = { path = "../lexer" }